### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by eladnava** [jsIsrael/JavaScript-Israel-Website#1]
Hey guys,
What's up? I heard you're looking for people to help with improving the site.

Given its current design, I think that the best course of action is to find a new template and copy all of the content over from the current site (it is a single page anyway, not very difficult).

Some great places to find awesome templates:
- [HTML5Up.net](http://html5up.net/) (free)
- [ThemeForest's Site Templates](http://themeforest.net/search?utf8=%E2%9C%93&term=&view=list&sort=sales&date=&category=site-templates&price_min=&price_max=&sales=&rating_min=) (cheap)

Here are a few that I really liked:
- http://pivot.mediumra.re/index.html
- http://pivot.mediumra.re/home-4.html
- http://pivot.mediumra.re/one-page.html
- http://themes.semicolonweb.com/html/canvas/index.php
- http://themes.semicolonweb.com/html/canvas/landing-2.php
- http://html5up.net/photon
- http://html5up.net/directive
- http://html5up.net/tessellate

I'd love to help with this -- it is not a very difficult task and should only take a few hours, once we decide on a new template. What do you say?

**Comment by shairez** [comment]
Hi @eladnava 
Thanks for picking up the gauntlet! :)

Do you feel comfortable with mocking it up in photoshop based on your favorite template? 

I believe it should be less work iterating over a mockup than CSS (which could get painful).

What do you think?

**Comment by eladnava** [comment]
@shairez No problem! :) Love what you guys are doing with the community.

Yes, I think a mockup is definitely a good idea. I'll put it together and upload it when I find some free time.

I think this template looks great and makes the most sense:
http://pivot.mediumra.re/one-page.html

And it even has an area for our top contributors:
![123](https://cloud.githubusercontent.com/assets/4394189/11812701/0df29cf6-a346-11e5-8bb4-77e906984acf.png)

It costs $18 - can we get a sponsor to pay for it once we decide it's good for us?

I'll prepare the mockup in the meantime.

**Comment by eladnava** [comment]
Hi @shairez 
Here is a mockup of the new JavaScript Israel site based on the Pivot template:

(Click it for a high-res full screenshot)
![mockup](https://cloud.githubusercontent.com/assets/4394189/11827392/9ed8f334-a394-11e5-953c-1d6b1ecd4cf8.jpg)

Notes:
- The main background is something me and @zivkr2 based off of a random photo in the [JavaScript Israel Facebook Page](https://www.facebook.com/groups/jsisrael/photos/). Let us know what you think / how to improve it / whether you have a higher quality or better photo.
- Logo - can we redesign it a bit / change the font so it fits the template?
- The text and slogans are changeable. I pretty much wrote the first thing that popped into my head. Open to suggestions.

The following sections are missing:
- Wanna Learn? / Wanna Help? / Wanna Sponsor? - I'll find a new way to display these sections once we have a green light on the template.
- Top Contributors / Organizers / Sponsors - People are missing, pending green light on the template.

What do you think? Anything else missing / needs changing?

**Comment by shairez** [comment]
First of all, great job so far!

Few things - 
1. I think we should consider keeping a "blueish" theme to match our group logo colors, so it's probably a thing of playing with some css values here and there.
2. I think the theme with the pages - http://pivot.mediumra.re/home-4.html is a more suitable direction looking forward.
3. Here's a nice quality picture
   ![p1010816](https://cloud.githubusercontent.com/assets/1430726/11859045/34f4a9b8-a470-11e5-9f30-40bf9696293e.JPG)
4. about the logo, I'll send you the source file once you'll start the redesign
5. Just a question, how maintainable / customizable these templates? in case we'll need to add stuff in the future / change css without "hacking" over the template etc... 
   I originally thought of using some static site generator, so it'll be easy to add content pages without duplicating stuff and without using wordpress.

What do you think?

**Comment by eladnava** [comment]
@shairez Thanks!
1. No problem, I'll change the red color scheme to a blue one.
2. I went with the default theme, http://pivot.mediumra.re/index.html, instead of the single page one I mentioned before. Is it fine? It has pagination as well (which I removed in the mockup to match the current site).
3. Great, we'll use it instead. (Coincidentally, I'm the guy in the green shirt there =) What are the chances?)
4. Excellent, thanks.
5. Very easy to change things. It's just .html files with some very well-documented CSS classes. I think it will be extremely trivial to add content pages (and they even provide lots of example pages for us to start from).

I have some free time this weekend -- any chance we can purchase the template by then?

**Comment by shairez** [comment]
@eladnava  just sent you an email with the purchased template and logo

Let me know if you need anything else

Thanks!

**Comment by shairez** [comment]
@eladnava you did an awesome job! 
I fixed small stuff here and there and merged

BTW, If you can, have a look on the upper left logo on the top of the page, it seems to be shrinking somehow, please check if it happens to you too.

Thanks again!

**Comment by eladnava** [comment]
@shairez thanks!

Regarding the logo, #4 fixes that weird bug.
