### ISSUE TITLE
Buy an additional domain

### ISSUE THREAD

**Issue by eladnava** [jsIsrael/JavaScript-Israel-Website#7]
Hey guys,
www.JavascriptIsrael.com is available and I think it would be nice if we could purchase it and have it redirect to www.jsisrael.com. You won't believe how many times I've accidentally entered entered javascriptisrael.com by accident when trying to navigate to the site, only to remember that the domain is actually jsisrael.com (which is a little bit confusing because the group is called "Javascript Israel").

The domain costs only $0.99 on GoDaddy:
https://uk.godaddy.com/domains/searchresults.aspx?tld=.COM&isc=goflis04&ci=99126&dpp_itc=DLP_OFFER_COM&tmskey=1dom_03&checkAvail=1&domainToCheck=javascriptisrael.com

What do you think? @shairez

**Comment by shairez** [comment]
Thanks @eladnava  !
we actually used to own this domain, but decided to stick with the shorter one
BTW, For regular customers (not new) like myself, it costs 12$, not that it's that much money, but still, I'm not sure about this one.

**Comment by eladnava** [comment]
OK cool, got it 👍
